# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_transmission.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amessage_transmission.proto\"\x9b\x01\n\x0eMessageRequest\x12\x16\n\x0esource_edge_id\x18\x01 \x01(\x03\x12\x13\n\x0b\x66rame_index\x18\x02 \x01(\x03\x12\x12\n\nstart_time\x18\x03 \x01(\t\x12\r\n\x05\x66rame\x18\x04 \x01(\t\x12\x13\n\x0bpart_result\x18\x05 \x01(\t\x12\x11\n\traw_shape\x18\x06 \x01(\t\x12\x11\n\tnew_shape\x18\x07 \x01(\t\"N\n\x0cMessageReply\x12\x16\n\x0e\x64\x65stination_id\x18\x01 \x01(\x03\x12\x14\n\x0clocal_length\x18\x02 \x01(\x03\x12\x10\n\x08response\x18\x03 \x01(\t\";\n\x0bInfoRequest\x12\x16\n\x0esource_edge_id\x18\x01 \x01(\x03\x12\x14\n\x0clocal_length\x18\x02 \x01(\x03\"9\n\tInfoReply\x12\x16\n\x0e\x64\x65stination_id\x18\x01 \x01(\x03\x12\x14\n\x0clocal_length\x18\x02 \x01(\x03\x32w\n\x13MessageTransmission\x12\x32\n\x0etask_processor\x12\x0f.MessageRequest\x1a\r.MessageReply\"\x00\x12,\n\x0eget_queue_info\x12\x0c.InfoRequest\x1a\n.InfoReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_transmission_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEREQUEST._serialized_start=31
  _MESSAGEREQUEST._serialized_end=186
  _MESSAGEREPLY._serialized_start=188
  _MESSAGEREPLY._serialized_end=266
  _INFOREQUEST._serialized_start=268
  _INFOREQUEST._serialized_end=327
  _INFOREPLY._serialized_start=329
  _INFOREPLY._serialized_end=386
  _MESSAGETRANSMISSION._serialized_start=388
  _MESSAGETRANSMISSION._serialized_end=507
# @@protoc_insertion_point(module_scope)
