# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_server import message_transfer_pb2 as message__transfer__pb2


class MessageTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.image_processor = channel.unary_unary(
                '/MessageTransfer/image_processor',
                request_serializer=message__transfer__pb2.MessageRequest.SerializeToString,
                response_deserializer=message__transfer__pb2.MessageReply.FromString,
                )


class MessageTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def image_processor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'image_processor': grpc.unary_unary_rpc_method_handler(
                    servicer.image_processor,
                    request_deserializer=message__transfer__pb2.MessageRequest.FromString,
                    response_serializer=message__transfer__pb2.MessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MessageTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def image_processor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MessageTransfer/image_processor',
            message__transfer__pb2.MessageRequest.SerializeToString,
            message__transfer__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
