# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16message_transfer.proto\"4\n\x0eMessageRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\t\x12\x13\n\x0b\x66rame_shape\x18\x02 \x01(\t\"3\n\x0cMessageReply\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x13\n\x0b\x66rame_shape\x18\x02 \x01(\t2F\n\x0fMessageTransfer\x12\x33\n\x0fimage_processor\x12\x0f.MessageRequest\x1a\r.MessageReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_transfer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEREQUEST._serialized_start=26
  _MESSAGEREQUEST._serialized_end=78
  _MESSAGEREPLY._serialized_start=80
  _MESSAGEREPLY._serialized_end=131
  _MESSAGETRANSFER._serialized_start=133
  _MESSAGETRANSFER._serialized_end=203
# @@protoc_insertion_point(module_scope)
