source:
 video_path: ./video_data/road.mp4
 rtsp:
  label: False
  account: your account
  password: your password
  ip_address: you camera ip
  channel: 1

client:
 #the frame interval
 interval: 1
 #the difference feature (pixel, edge, area, corner).
 feature: edge
 #the difference threshold
 diff_thresh: 0.005
 #the queue maxsize
 local_queue_maxsize: 10
 #the queue threshold for offloading
 queue_thresh: 5
 #Number of worker threads to offloading thread pool
 offloading_max_worker: 2
 frame_cache_maxsize: 100
 #regularly update queue info (second)
 regular: 10
 small_model_name: fasterrcnn_mobilenet_v3_large_320_fpn
 #select the offloading policy
 policy: Edge-Cloud-Threshold
 #change frame resolution using frame new height
 new_height:
  #offload to another edge node [1080, 720], default 720
  another: 720
  #option to offload directly to the cloud [1080, 720, 480], default 480
  directly_cloud: 480
  #offload to the cloud after local inference [1080, 720, 480], default 720
  local_cloud: 720
  #The task from another edge node is offloaded to the cloud after local inference [720, 480], default 720
  another_cloud: 720
 #the quality of the transmitted frame
 quality:
  #offload to another edge node [95, 85], default 85
  another: 85
  #Option to offload directly to the cloud [85, 95], default 85
  directly_cloud: 85
  #offload to the cloud after local inference [85, 95], default 95
  local_cloud: 95
  #The task from another edge node is offloaded to the cloud after local inference, default 85.
  another_cloud: 85
 #server_ip
 server_ip: '127.0.0.1:50051'
 #edge nodes
 edge_id: 1
 edge_num: 2
 edges: ['localhost:50050', 'localhost:50050']

server:
 server_id: 0
 large_model_name: fasterrcnn_mobilenet_v3_large_fpn
 #the queue maxsize
 local_queue_maxsize: 10

#database config
database:
 connection: {'user': 'root', 'password': 'root', 'host': '127.0.0.1', 'raise_on_warnings': True}
 database_name: 'mydatabase'
 tables: [edge1, edge2]
 table_description: "CREATE TABLE `{}` (`index` int NOT NULL, `start_time` timestamp(6) NOT NULL,`end_time` timestamp(6) NOT NULL, `result` text, PRIMARY KEY(`index`))"
 insert_description: "INSERT INTO `{}` (`index`, `start_time`, `end_time`, `result`) VALUES (%s ,%s, %s, %s);"

