source:
 video_path: ./video_data/dayroad.mp4
 rtsp:
  label: False
  account: your account
  password: your password
  ip_address: you camera ip
  channel: 1

client:
 #the frame interval
 interval: 2
 #the difference feature (pixel, edge, area, corner).
 feature: edge
 #the difference threshold
 diff_lable: True
 diff_thresh: 0.01
 #timeout drop frame
 timeout_drop: 4
 #the queue maxsize
 local_queue_maxsize: 10
 #the queue threshold for offloading
 queue_thresh: 5
 #Number of worker threads to offloading thread pool
 offloading_max_worker: 1
 frame_cache_maxsize: 100
 #regularly update queue info (second)
 regular: 3
 small_model_name: fasterrcnn_mobilenet_v3_large_fpn
 #select the offloading policy
 policy: Edge-Cloud-Assisted
 #change frame resolution using frame new height
 new_height:
  #offload to another edge node [1080, 720], default 720
  another: 720
  #option to offload directly to the cloud [1080, 720, 480], default 480
  directly_cloud: 720
  #offload to the cloud after local inference [1080, 720, 480], default 720
  local_cloud: 720
  #The task from another edge node is offloaded to the cloud after local inference [720, 480], default 720
  another_cloud: 720
 #the quality of the transmitted frame
 quality:
  #offload to another edge node [90, 85], default 85
  another: 90
  #Option to offload directly to the cloud [85, 95], default 85
  directly_cloud: 85
  #offload to the cloud after local inference [85, 95], default 95
  local_cloud: 95
  #The task from another edge node is offloaded to the cloud after local inference, default 85.
  another_cloud: 90
 #server_ip
 server_ip: 'server ip'
 #edge nodes
 edge_id: 1
 edge_num: 1
 edges: ['127.0.0.1:50051',]

server:
 server_id: 0
 large_model_name: fasterrcnn_resnet50_fpn
 #timeout drop frame
 timeout_drop: 4
 #the queue maxsize
 local_queue_maxsize: 10
 data_queue_maxsize: 10

#database config
database:
 connection: {'user': 'root', 'password': 'root', 'host': 'database ip', 'raise_on_warnings': True}
 database_name: 'mydatabase'
 tables: [edge1]
 table_description: "CREATE TABLE `{}` (`index` int NOT NULL, `start_time` timestamp(6) NOT NULL,`end_time` timestamp(6) NOT NULL, `result` text, `mark` text , PRIMARY KEY(`index`)) ENGINE=InnoDB"
 insert_description: "INSERT INTO `{}` (`index`, `start_time`, `end_time`, `result`, `mark`) VALUES (%s ,%s, %s, %s, %s);"
 select_description: "SELECT `index`, `start_time`, `end_time`, `result`, `mark` FROM `{}`;"

